##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_widgets
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_widgets
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/RobertMollentze
- https://github.com/sponsors/robmllze
description: A collection of practical widgets that are neither material nor cupertino.
version: 0.2.12
topics:
  - design
  - modular
  - theme
  - user-interface
  - widgets

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  fluentui_system_icons: ^1.1.273
  visibility_detector: ^0.4.0+2

  df_color: ^0.1.6
  df_di: ^0.15.2
  df_generate_dart_models_core: ^0.9.22
  df_pod: ^0.18.10
  df_scalable: ^0.9.6
  df_debouncer: ^0.4.16
  

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^6.0.0

